services:
  # 1. Backend (Express.js)
  server:
    image: node:24.12.0
    container_name: warican_server
    user: node
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=database
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    command: sleep infinity
    depends_on:
      - database

  # 2. Frontend (Vue.js)
  client:
    image: node:24.12.0
    container_name: warican_client
    user: node
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    command: sleep infinity

  # 3. MySQL Server
  database:
    image: mysql:8.0
    container_name: warican_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/data:/var/lib/mysql
      - ./database/config/app.cnf:/etc/mysql/conf.d/app.cnf
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
