export const COMMON_CURRENCIES = [
  { code: 'JPY', name: '日本円', symbol: '¥' },
  { code: 'USD', name: '米ドル', symbol: '$' },
  { code: 'EUR', name: 'ユーロ', symbol: '€' },
  { code: 'GBP', name: '英ポンド', symbol: '£' },
  { code: 'CNY', name: '人民元', symbol: '¥' },
  { code: 'KRW', name: '韓国ウォン', symbol: '₩' },
  { code: 'AUD', name: '豪ドル', symbol: 'A$' },
  { code: 'CAD', name: 'カナダドル', symbol: 'C$' },
  { code: 'CHF', name: 'スイスフラン', symbol: 'CHF' },
  { code: 'SEK', name: 'スウェーデンクローナ', symbol: 'kr' },
  { code: 'NZD', name: 'ニュージーランドドル', symbol: 'NZ$' },
  { code: 'MXN', name: 'メキシコペソ', symbol: 'MX$' },
  { code: 'SGD', name: 'シンガポールドル', symbol: 'S$' },
  { code: 'HKD', name: '香港ドル', symbol: 'HK$' },
  { code: 'NOK', name: 'ノルウェークローネ', symbol: 'kr' },
  { code: 'TRY', name: 'トルコリラ', symbol: '₺' },
  { code: 'RUB', name: 'ロシアルーブル', symbol: '₽' },
  { code: 'INR', name: 'インドルピー', symbol: '₹' },
  { code: 'BRL', name: 'ブラジルレアル', symbol: 'R$' },
  { code: 'THB', name: 'タイバーツ', symbol: '฿' },
  { code: 'TWD', name: '台湾ドル', symbol: 'NT$' },
  { code: 'DKK', name: 'デンマーククローネ', symbol: 'kr' },
  { code: 'PLN', name: 'ポーランドズウォティ', symbol: 'zł' },
  { code: 'CZK', name: 'チェココルナ', symbol: 'Kč' },
  { code: 'HUF', name: 'ハンガリーフォリント', symbol: 'Ft' },
  { code: 'IDR', name: 'インドネシアルピア', symbol: 'Rp' },
  { code: 'PHP', name: 'フィリピンペソ', symbol: '₱' },
  { code: 'MYR', name: 'マレーシアリンギット', symbol: 'RM' },
  { code: 'VND', name: 'ベトナムドン', symbol: '₫' },
  { code: 'ZAR', name: '南アフリカランド', symbol: 'R' },
  { code: 'AED', name: 'UAEディルハム', symbol: 'د.إ' },
  { code: 'SAR', name: 'サウジアラビアリヤル', symbol: 'ر.س' },
  { code: 'ILS', name: 'イスラエル新シェケル', symbol: '₪' },
  { code: 'ARS', name: 'アルゼンチンペソ', symbol: 'ARS$' },
  { code: 'CLP', name: 'チリペソ', symbol: 'CLP$' },
  { code: 'COP', name: 'コロンビアペソ', symbol: 'COP$' },
];

export const COMMON_CURRENCY_CODES = COMMON_CURRENCIES.map((currency) => currency.code);
